# Generated by Django 2.2.2 on 2020-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
