# Generated by Django 2.2.2 on 2020-07-03 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0010_auto_20200630_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(default='', related_name='commentsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
