# Generated by Django 2.2.2 on 2020-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0016_auto_20200703_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(upload_to='Profiles'),
        ),
    ]
