# Generated by Django 2.2.2 on 2020-07-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0017_auto_20200704_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='default/profile.png', upload_to='Profiles'),
        ),
    ]
